version: '2'
services:
    blog2-app:
        image: blog2
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://blog2-mysql:3306/blog2?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    blog2-mysql:
        extends:
            file: mysql.yml
            service: blog2-mysql
